-- Urban Nest - Supabase PostgreSQL schema
-- Run this entire file in Supabase Dashboard -> SQL Editor.
-- This replaces the original MySQL database/apartment_rental.sql.

DROP TABLE IF EXISTS apartment_images CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS leave_requests CASCADE;
DROP TABLE IF EXISTS admin_promotion_verifications CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS rentals CASCADE;
DROP TABLE IF EXISTS rental_requests CASCADE;
DROP TABLE IF EXISTS apartments CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    reset_token VARCHAR(100) DEFAULT NULL,
    reset_expires TIMESTAMP DEFAULT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin','tenant')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tenants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    contact_number VARCHAR(30) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tenant_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE apartments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_number VARCHAR(20) NOT NULL UNIQUE,
    type VARCHAR(30) NOT NULL CHECK (type IN ('Studio','1 Bedroom','2 Bedroom')),
    monthly_rent NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Available' CHECK (status IN ('Available','Reserved','Occupied')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE apartment_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id INTEGER NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_apartment_image_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE
);
CREATE INDEX idx_apartment_images ON apartment_images(apartment_id);

CREATE TABLE rental_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    apartment_id INTEGER NOT NULL,
    request_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
    approved_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_request_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE
);
CREATE INDEX idx_request_status ON rental_requests(status);
CREATE INDEX idx_request_tenant_status ON rental_requests(tenant_id,status);

CREATE TABLE rentals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    apartment_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    next_due_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    monthly_rent NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Ended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rental_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_rental_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE
);
CREATE INDEX idx_rental_tenant_status ON rentals(tenant_id,status);
CREATE INDEX idx_rental_apartment_status ON rentals(apartment_id,status);

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id INTEGER NOT NULL,
    tenant_id INTEGER NOT NULL,
    apartment_id INTEGER NOT NULL,
    rent_amount NUMERIC(10,2) NOT NULL,
    due_date DATE NOT NULL,
    payment_date DATE NOT NULL,
    early_discount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    late_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('Pending','Early Payment','Paid','Overdue')),
    payment_method VARCHAR(20) NOT NULL DEFAULT 'Cash' CHECK (payment_method IN ('Card','QR Payment','Cash')),
    reference_number VARCHAR(80) DEFAULT NULL,
    received_at TIMESTAMP DEFAULT NULL,
    received_by INTEGER DEFAULT NULL,
    receipt_sent_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_received_by FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_payment_tenant ON payments(tenant_id);
CREATE INDEX idx_payment_status ON payments(status);
CREATE INDEX idx_payment_date ON payments(payment_date);
CREATE INDEX idx_payment_method ON payments(payment_method);

CREATE TABLE password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_password_reset_active ON password_resets(user_id,used_at,expires_at);

CREATE TABLE admin_promotion_verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by INTEGER NOT NULL,
    target_user_id INTEGER NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_promo_requester FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_promo_target FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_admin_promo_lookup ON admin_promotion_verifications(requested_by,verified_at,expires_at);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    admin_id INTEGER NOT NULL,
    sender_role VARCHAR(20) NOT NULL CHECK (sender_role IN ('tenant','admin')),
    message TEXT NOT NULL,
    is_read SMALLINT NOT NULL DEFAULT 0 CHECK (is_read IN (0,1)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_admin FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_message_tenant_date ON messages(tenant_id,created_at);
CREATE INDEX idx_message_admin_read ON messages(admin_id,is_read);

CREATE TABLE leave_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    rental_id INTEGER NOT NULL,
    apartment_id INTEGER NOT NULL,
    request_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
    processed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leave_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_leave_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
    CONSTRAINT fk_leave_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE
);
CREATE INDEX idx_leave_status ON leave_requests(status);
CREATE INDEX idx_leave_tenant_status ON leave_requests(tenant_id,status);

-- Demo accounts. Change these passwords from the application after installation.
INSERT INTO users (username,email,password,role) VALUES
('admin','admin@apartment.local','$2y$12$chm25l8QYZfpo/E/LtdS5eOtvUkIX61cTFF8T.ab5qp0rzFEqjH5O','admin'),
('juan','juan@example.com','$2y$12$6oiKjRYTuad2MJSfnz/Dy.vG93Dv7GHcdglq/wVzt1dup5AOeW3xW','tenant'),
('maria','maria@example.com','$2y$12$6oiKjRYTuad2MJSfnz/Dy.vG93Dv7GHcdglq/wVzt1dup5AOeW3xW','tenant');

INSERT INTO tenants (user_id,full_name,contact_number,address) VALUES
((SELECT id FROM users WHERE username='juan'),'Juan Dela Cruz','09171234567','Pateros, Metro Manila'),
((SELECT id FROM users WHERE username='maria'),'Maria Santos','09181234567','Taguig City, Metro Manila');

INSERT INTO apartments (apartment_number,type,monthly_rent,status) VALUES
('A101','Studio',6000.00,'Available'),
('A102','1 Bedroom',8000.00,'Occupied'),
('A103','2 Bedroom',10000.00,'Available'),
('A104','1 Bedroom',8000.00,'Available'),
('A105','Studio',6000.00,'Available'),
('A106','2 Bedroom',10000.00,'Occupied');

INSERT INTO rentals (tenant_id,apartment_id,start_date,next_due_date,monthly_rent,status) VALUES
((SELECT id FROM tenants WHERE full_name='Juan Dela Cruz'),
 (SELECT id FROM apartments WHERE apartment_number='A102'),
 '2026-08-01','2026-09-01',8000.00,'Active');

INSERT INTO payments (rental_id,tenant_id,apartment_id,rent_amount,due_date,payment_date,early_discount,late_fee,total_amount,status) VALUES
((SELECT id FROM rentals WHERE tenant_id=(SELECT id FROM tenants WHERE full_name='Juan Dela Cruz') AND status='Active'),
 (SELECT id FROM tenants WHERE full_name='Juan Dela Cruz'),
 (SELECT id FROM apartments WHERE apartment_number='A102'),
 8000.00,'2026-08-05','2026-08-05',0.00,0.00,8000.00,'Paid');
